const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  orders: state => state.order.orders,
  totalOfOrder: state => state.order.totalOfOrder,
  currentPageOfOrder: state => state.order.currentPageOfOrder,
  orderSelected: state => state.order.orderSelected,
  clerks: state => state.clerk.clerks,
  clerksCurrentPage: state => state.clerk.currentPage,
  totalOfClerk: state => state.clerk.totalOfClerk,
  parkingLotsInDashboard: state => state.dashboard.parkingLotsInDashboard,
  totalOfParkingLotInDashboard: state => state.dashboard.totalOfParkingLotInDashboard,
  currentPageOfParkingLotInDashboard: state => state.dashboard.currentPageOfParkingLotInDashboard
}
export default getters
